name: Unit-Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        #Set DATABASE_URL for environment
      - name: Set DATABASE_URL
        run: |
          echo  "repository variable : $DATABASE_URL"
        env:
          DATABASE_URL: ${{vars.DATABASE_URL}}
        #Set NODE_ENV for environment
      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm
        # Install dependencies
      - name: Install dependencies
        run: pnpm install
      - name: test
        run: pnpm test
