name: Unit-Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env: # Setting the environment variable globally for all steps
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        #Set NODE_ENV for environment
      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm
        # Install dependencies
      - name: Install dependencies
        run: pnpm install
      - name: test
        run: pnpm test
